version: '3'
services:
  store:
    build:
      context: ./store
      dockerfile: Dockerfile
    volumes:
      - ./store:/var/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    depends_on:
      - postgres
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/app
      - ./private:/private
    environment:
      - DEBUG=*
      - HTTPS_PORT=55555
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 55555:55555
    command: >
      yarn start
  daemon:
    build:
      context: ./daemon
      dockerfile: Dockerfile
    volumes:
      - ./daemon:/var/app
    environment:
      - DEBUG=*
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    command: >
      yarn start
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
volumes:
  pgdata: {}
